//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Information.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Personal_Information.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _01 {
            get {
                object obj = ResourceManager.GetObject("01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _11 {
            get {
                object obj = ResourceManager.GetObject("11", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1249001 {
            get {
                object obj = ResourceManager.GetObject("1249001", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12490011 {
            get {
                object obj = ResourceManager.GetObject("12490011", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _12490012 {
            get {
                object obj = ResourceManager.GetObject("12490012", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_1199095122_cKzdqeA6EfoK4H3nK03ZAUzsGdRwiKpy {
            get {
                object obj = ResourceManager.GetObject("360_F_1199095122_cKzdqeA6EfoK4H3nK03ZAUzsGdRwiKpy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_168204719_aWhXPHpnQGmwyZ9BSaZAdfMcvNWqle7B {
            get {
                object obj = ResourceManager.GetObject("360_F_168204719_aWhXPHpnQGmwyZ9BSaZAdfMcvNWqle7B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_542731787_npIDENXs9NMkl1mtyHKj8De2WBL2vnFW {
            get {
                object obj = ResourceManager.GetObject("360_F_542731787_npIDENXs9NMkl1mtyHKj8De2WBL2vnFW", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_542731787_npIDENXs9NMkl1mtyHKj8De2WBL2vnFW1 {
            get {
                object obj = ResourceManager.GetObject("360_F_542731787_npIDENXs9NMkl1mtyHKj8De2WBL2vnFW1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_603500239_prjmq4c6rdtUE8JdywxRUlwWEcu8k5TD {
            get {
                object obj = ResourceManager.GetObject("360_F_603500239_prjmq4c6rdtUE8JdywxRUlwWEcu8k5TD", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_603500239_prjmq4c6rdtUE8JdywxRUlwWEcu8k5TD1 {
            get {
                object obj = ResourceManager.GetObject("360_F_603500239_prjmq4c6rdtUE8JdywxRUlwWEcu8k5TD1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _360_F_896346393_QKnKIR9pTAg7fPLCeY4gXmdYqj7YGV8p {
            get {
                object obj = ResourceManager.GetObject("360_F_896346393_QKnKIR9pTAg7fPLCeY4gXmdYqj7YGV8p", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _42282747836a723b1e666d063b3dd098 {
            get {
                object obj = ResourceManager.GetObject("42282747836a723b1e666d063b3dd098", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _42282747836a723b1e666d063b3dd0981 {
            get {
                object obj = ResourceManager.GetObject("42282747836a723b1e666d063b3dd0981", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _57d11c8bbec667f5601abfb3bb6f8277 {
            get {
                object obj = ResourceManager.GetObject("57d11c8bbec667f5601abfb3bb6f8277", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_background_template_for_style_design_267606 {
            get {
                object obj = ResourceManager.GetObject("abstract_background_template_for_style_design_267606", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap abstract_background_template_for_style_design_2676061 {
            get {
                object obj = ResourceManager.GetObject("abstract_background_template_for_style_design_2676061", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap artistic_blurry_colorful_wallpaper_background_58702_8169 {
            get {
                object obj = ResourceManager.GetObject("artistic-blurry-colorful-wallpaper-background_58702-8169", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_1696064_640 {
            get {
                object obj = ResourceManager.GetObject("background-1696064_640", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap background_1696064_6401 {
            get {
                object obj = ResourceManager.GetObject("background-1696064_6401", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Blog_How_Background_Checks_Work_When_Hiring_Employees_Globally {
            get {
                object obj = ResourceManager.GetObject("Blog-How-Background-Checks-Work-When-Hiring-Employees-Globally", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_curve_frame_template_vector_53876_165851 {
            get {
                object obj = ResourceManager.GetObject("blue-curve-frame-template-vector_53876-165851", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_curve_frame_template_vector_53876_1658511 {
            get {
                object obj = ResourceManager.GetObject("blue-curve-frame-template-vector_53876-1658511", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blue_gradient_background_blue_blurry_background_blue_pastel_gradient_wallpaper_613001_6441 {
            get {
                object obj = ResourceManager.GetObject("blue-gradient-background-blue-blurry-background-blue-pastel-gradient-wallpaper_61" +
                        "3001-6441", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap desktop_wallpaper_simple_backgrounds_for_powerpoint_presentation_red_clipartgram_background_power_point_simpel_thumbnail {
            get {
                object obj = ResourceManager.GetObject("desktop-wallpaper-simple-backgrounds-for-powerpoint-presentation-red-clipartgram-" +
                        "background-power-point-simpel-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ea4f6d3a64c3cbce3877604bb7a4a152 {
            get {
                object obj = ResourceManager.GetObject("ea4f6d3a64c3cbce3877604bb7a4a152", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FfG96_HXgAAXHz_ {
            get {
                object obj = ResourceManager.GetObject("FfG96-HXgAAXHz-", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap FfG96_HXgAAXHz_1 {
            get {
                object obj = ResourceManager.GetObject("FfG96-HXgAAXHz-1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HD_wallpaper_adobe_creative_suite_ppt_background_for_microsoft_powerpoint_adobe_hop_hop_adobe_creative_suite_adobe_creative_cloud {
            get {
                object obj = ResourceManager.GetObject("HD-wallpaper-adobe-creative-suite-ppt-background-for-microsoft-powerpoint-adobe-h" +
                        "op-hop-adobe-creative-suite-adobe-creative-cloud", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG_20250518_WA0021_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("IMG-20250518-WA0021-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vintage_and_shabby_paper_textures_high_resolution_backgrounds_image_626168 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vintage-and-shabby-paper-textures-high-resolution-backgrounds-image_62616" +
                        "8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pngtree_vintage_and_shabby_paper_textures_high_resolution_backgrounds_image_6261681 {
            get {
                object obj = ResourceManager.GetObject("pngtree-vintage-and-shabby-paper-textures-high-resolution-backgrounds-image_62616" +
                        "81", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap professional_simple_corporate_square_template_background_with_empty_space_for_text_orange_and_blue_template_background_vector {
            get {
                object obj = ResourceManager.GetObject("professional-simple-corporate-square-template-background-with-empty-space-for-tex" +
                        "t-orange-and-blue-template-background-vector", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap purple_watercolor_background_texture_digital_199112_98 {
            get {
                object obj = ResourceManager.GetObject("purple-watercolor-background-texture-digital_199112-98", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_blue_curve_background_vector_business_53876_169278 {
            get {
                object obj = ResourceManager.GetObject("simple-blue-curve-background-vector-business_53876-169278", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_blue_gradient_background_vector_business_53876_161578 {
            get {
                object obj = ResourceManager.GetObject("simple-blue-gradient-background-vector-business_53876-161578", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap simple_blue_gradient_background_vector_business_53876_1615781 {
            get {
                object obj = ResourceManager.GetObject("simple-blue-gradient-background-vector-business_53876-1615781", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap steel_blue_abstract_background_wallpaper_image_53876_104016 {
            get {
                object obj = ResourceManager.GetObject("steel-blue-abstract-background-wallpaper-image_53876-104016", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap technology_background_presentation_edit_online {
            get {
                object obj = ResourceManager.GetObject("technology-background-presentation-edit-online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tocpat7_02 {
            get {
                object obj = ResourceManager.GetObject("tocpat7_02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tocpat7_021 {
            get {
                object obj = ResourceManager.GetObject("tocpat7_021", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vector_background_with_customizable_colors_geometric_shapes_98100_3983 {
            get {
                object obj = ResourceManager.GetObject("vector-background-with-customizable-colors-geometric-shapes_98100-3983", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vector_background_with_customizable_colors_geometric_shapes_98100_39831 {
            get {
                object obj = ResourceManager.GetObject("vector-background-with-customizable-colors-geometric-shapes_98100-39831", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vector_background_with_customizable_colors_geometric_shapes_98100_39832 {
            get {
                object obj = ResourceManager.GetObject("vector-background-with-customizable-colors-geometric-shapes_98100-39832", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vector_background_with_customizable_colors_geometric_shapes_98100_39833 {
            get {
                object obj = ResourceManager.GetObject("vector-background-with-customizable-colors-geometric-shapes_98100-39833", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vector_design_background_blue_modern_luxury_921039_3825 {
            get {
                object obj = ResourceManager.GetObject("vector-design-background-blue-modern-luxury_921039-3825", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap vibrant_simple_background_with_white_space_custom_content_98100_4177 {
            get {
                object obj = ResourceManager.GetObject("vibrant-simple-background-with-white-space-custom-content_98100-4177", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap watercolor_pastel_blue_ombre_background_texture_sky_blue_gradient_backdrop_photo {
            get {
                object obj = ResourceManager.GetObject("watercolor-pastel-blue-ombre-background-texture-sky-blue-gradient-backdrop-photo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap winter_blue_pink_gradient_background_vector_53876_117275 {
            get {
                object obj = ResourceManager.GetObject("winter-blue-pink-gradient-background-vector_53876-117275", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
